accounts/urls.py
from django.urls import path
from accounts.views import *

app_name = 'accounts'

urlpatterns = [
    path('signup',signup, name='signup'),
    path('signin', signin, name='signin'),
]

board/urls.py
from django.contrib import admin
from django.urls import path, include
<<<<<<< HEAD

urlpatterns = [
    path('admin/', admin.site.urls),
    path('search/', include(('search.urls', 'search'), namespace='search')),
=======
<<<<<<< HEAD

urlpatterns = [
    path('admin/', admin.site.urls),
] + [
    path('board/', include("bulletin.urls"))
>>>>>>> origin/accounts
]
=======



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts'))
]
>>>>>>> origin/accounts

bulletin/urls.py
from django.urls import path

from bulletin import views

appname= "bulletin"

urlpatterns = [
    path('', views.documentList, name='board'),
    path('post/', views.newPost, name="new_post"),
    path('<int:id>/', views.detailView, name='document'),
    path('<int:id>/delete/', views.deleteDoc, name='delete_document'),
    path('<int:id>/modify/', views.modifyDoc, name='modify_document')

]

search/urls.py
from django.urls import path
from search import views

app_name = 'search'

urlpatterns = [
    path('', views.test, name='test'),
    path('result/', views.search, name='search')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

bulletin/models.py
from django.contrib.auth.models import AbstractUser, User
from django.db import models



class Document (models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    #@TODO 유저 이름 맞추기
    author = models.ForeignKey(User ,on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Comment (models.Model):
    text = models.CharField(max_length=300)
    doc = models.ForeignKey(Document, on_delete=models.CASCADE)
    #@TODO 유저 이름 맞추기
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
# Create your models here.

search/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']


class LoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']

bulletin/forms.py
from django import forms

from bulletin.models import Document


class PostForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ['title', 'content']

accounts/views.py
from django.contrib.auth import login, authenticate
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


# Create your views here.
from accounts.forms import UserForm, LoginForm


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'accounts/index.html')
        else:
            err = form.error_messages.values()
            return render(request, 'accounts/err.html', {'form': form, 'err':err})
    else:
        form = UserCreationForm()
        form.fields['username'].help_text= None
        form.fields['password1'].help_text= None
        form.fields['password2'].help_text= None
        return render(request, 'accounts/signup.html', {'form': form})

def signin(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username = username, password = password)
        if user is not None:
            login(request, user)
            return render(request,'accounts/suc.html')
        else:
            return HttpResponse('로그인 실패. 다시 시도 해보세요.')
    else:
        form = LoginForm()
        return render(request, 'accounts/signin.html', {'form': form})

bulletin/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect

from bulletin.forms import PostForm
from .models import Document
# Create your views here.

def documentList(request):
    docs = Document.objects.all()
    pages = Paginator(docs, 10)
    page = request.GET.get('page')
    list = pages.get_page(page)

    return render(request, 'bulletin/docList.html', {
        "list": list
    })

def detailView(request, id):
    doc = get_object_or_404(Document, pk=id)
    return render(request, 'bulletin/detail.html', {
        "doc": doc
    })

@login_required
def newPost(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('document', id=post.id)

    else:
        form = PostForm()
        return render(request, 'newPost.html', {
            'form':form
        })

# 수정, 삭제


@login_required
def deleteDoc(request, id):
    pass


@login_required
def modifyDoc(request, id):
    pass

search/views.py
from django.shortcuts import render, get_object_or_404, redirect
# from blog.models import Post
from django.contrib.auth.models import User

# Create your views here.
def test(request):
    return render(request, 'search/search_main.html')

def search(request):
    category = request.GET.get('choices', '')
    print(category)

    if category == 'Title':
        qs = Post.objects.all()
        q = request.GET.get('q', '')
        if q:
            result = []
            qs = qs.filter(title__icontains=q)
            for qp in qs:
                result.append(get_object_or_404(Post, pk=qp.id))
            return render(request, 'search/search_result.html', {
                'result': result,
            })

    elif category == 'Content':
        qs = Post.objects.all()
        q = request.GET.get('q', '')
        if q:
            result = []
            qs = qs.filter(content__icontains=q)
            for qp in qs:
                result.append(get_object_or_404(Post, pk=qp.id))
            return render(request, 'search/search_result.html', {
                'result': result,
            })

    if category == 'User':
        qs = User.objects.all()
        q = request.GET.get('q', '')
        if q:
            result = []
            qs = qs.filter(username__icontains=q)
            for qp in qs:
                result.append(get_object_or_404(User, pk=qp.id))
            return render(request, 'search/search_result.html', {
                'result': result,
                'q': q,
            })


    else:
        return redirect('search:test')

accounts/templates/accounts/err.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>error</title>
</head>
<body>
<h1>error</h1>

{% if err %}
    {% for erm in err %}
    {{ erm }}<br/>
    {% endfor %}
{% endif %}
</body>
</html>

accounts/templates/accounts/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Index</title>
</head>
<body>

<h1>가입성공</h1>

</body>
</html>

accounts/templates/accounts/signin.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Signin</title>
</head>
<body>

<h1> Sign In </h1><br/>
<form method="post" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="로그인" />
</form>

</body>
</html>

accounts/templates/accounts/signup.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Signup</title>
</head>
<body>

<h1> Sign Up </h1><br/>

<form method="post" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="회원가입" />
</form>



</body>
</html>

accounts/templates/accounts/suc.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login Success</title>
</head>
<body>
<h1>로그인 성공!</h1>
</body>
</html>

bulletin/templates/bulletin/detail.html
{# @TODO 공통된 레이아웃 적용 #}

<div class="document-container">
    <div class="doc-row title">{{ doc.title }}</div>
    <div class="doc-row content">{{ doc.content }}</div>
    <div class="doc-row footer">
        <span class="doc__author">{{ doc.author }}</span>
        <span class="doc__date">{{ doc.update_at }}</span>
    </div>
    <div class="doc-row comments">
        {% for comment in doc.comment_set.all %}
            <div class="comment-row">
                <div class="comment-col content">
                    {{ comment.text }}
                </div>
                <div class="comment-col info">
                    <span class="comment__author">
                        {{ comment.author }}
                    </span>
                    <span class="comment__date">
                        {{ comment.updated_at }}
                    </span>
                </div>
            </div>
        {% endfor %}
    </div>

</div>

bulletin/templates/bulletin/docList.html
{# @TODO include 해야하는 틀 만들기 #}
<div class="board-container">
    <div class="board-header">
        <div class="board-col">TITLE</div>
        <div class="board-col">AUTHOR</div>
        <div class="board-col">DATE</div>
    </div>
    {% for doc in list %}
        <a href="{% url 'document' doc.id %}">
            <div class="board-row">
                <div class="board-col">{{ doc.title }}</div>
                <div class="board-col">{{ doc.author }}</div>
                <div class="board-col">{{ doc.updated_at }}</div>
            </div>
        </a>
    {% endfor %}
</div>

<div class="pagination">
    <span class="step-links">
        {% if list.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ list.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ list.number }} of {{ list.paginator.num_pages }}.
        </span>

        {% if list.has_next %}
            <a href="?page={{ list.next_page_number }}">next</a>
            <a href="?page={{ list.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

<a href="{% url "" %}" class="write">글쓰기</a>

<style>
    .board-container {
        width:90%;
        height:50%;
    }
    .board-col {
        display: inline-block;
    }
    .board-container .board-row {
        display: flex;
        justify-content: space-between;
        align-items: center;
        border-bottom: solid 1px gray;
        height: 35px;
    }

    .board-header {
        display: flex;
        justify-content: space-between;
        border-bottom: solid 2px black;
    }
</style>

search/templates/search/search_main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>HELLO SEARCH</h1>
    <form action="{% url 'search:search' %}?next={{ request.path }}" method="get">

        <select data-trigger="" name="choices">
            <option placeholder="">Option</option>
            <option>Title</option>
            <option>Content</option>
            <option>User</option>
        </select>
        <input id="search" type="text" placeholder="Enter Keywords?" name="q" value="{{ q }}" autofocus/>
        <button type="submit"></button>
    </form>
</body>
</html>

search/templates/search/search_result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1> TEST</h1>
    <h2>{{ q }}..에 대한 검색결과 {{ result|length }}건</h2>

    <ul>
    {% for each_post in result %}
        <li>{{ each_post }}</li>
    {% endfor %}
    </ul>
</body>
</html>